/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SocialMediaRouteImport } from './routes/social-media'
import { Route as TrajetoriaRouteImport } from './routes/trajetoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaRoute = SocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => rootRouteImport,
} as any)
const TrajetoriaRoute = TrajetoriaRouteImport.update({
  id: '/trajetoria',
  path: '/trajetoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/sobre': typeof SobreRoute
  '/social-media': typeof SocialMediaRoute
  '/trajetoria': typeof TrajetoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/sobre': typeof SobreRoute
  '/social-media': typeof SocialMediaRoute
  '/trajetoria': typeof TrajetoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/sobre': typeof SobreRoute
  '/social-media': typeof SocialMediaRoute
  '/trajetoria': typeof TrajetoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/contato'
    | '/projetos'
    | '/sobre'
    | '/social-media'
    | '/trajetoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contato'
    | '/projetos'
    | '/sobre'
    | '/social-media'
    | '/trajetoria'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/contato'
    | '/projetos'
    | '/sobre'
    | '/social-media'
    | '/trajetoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ContatoRoute: typeof ContatoRoute
  ProjetosRoute: typeof ProjetosRoute
  SobreRoute: typeof SobreRoute
  SocialMediaRoute: typeof SocialMediaRoute
  TrajetoriaRoute: typeof TrajetoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media': {
      id: '/social-media'
      path: '/social-media'
      fullPath: '/social-media'
      preLoaderRoute: typeof SocialMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trajetoria': {
      id: '/trajetoria'
      path: '/trajetoria'
      fullPath: '/trajetoria'
      preLoaderRoute: typeof TrajetoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ContatoRoute: ContatoRoute,
  ProjetosRoute: ProjetosRoute,
  SobreRoute: SobreRoute,
  SocialMediaRoute: SocialMediaRoute,
  TrajetoriaRoute: TrajetoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
